-- AlterTable
ALTER TABLE "ProductImage" ADD COLUMN     "offsetX" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "offsetY" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "scale" DOUBLE PRECISION NOT NULL DEFAULT 1;
